jkl <- read.csv("C:/Users/SHYAMSUNDER GOWD/Desktop/exda/exdata_data_household_power_consumption/household_power_consumption.txt", sep=";", na.strings="?", stringsAsFactors=FALSE)
jkl$Date<-paste(jkl$Date,jkl$Time)
jkl$Date<-strptime(jkl$Date,format = "%d/%m/%Y %H:%M:%S")
ac<-subset(jkl,Date>="2007-01-01"&Date<"2007-01-03")
png(file = "plot3.png",width = 480,height =480)
with(ac,plot(Date,Sub_metering_3,type = "l",ylab = "Sub metering"))
lines(ac$Date,ac$Sub_metering_2, col="blue")
lines(ac$Date,ac$Sub_metering_1, col="red")
legend("topleft",legend = c("Submetering 3","Submetering 2","Sub metering 1"),col=c("Black","Blue","Red"),lty = 1)
dev.off()
